const products = [
  {
    _id: 1,
    name: 'Chocolate Chip',
    image: './images/chocolatechip.jpg',
    description: 'A delicious soft chocolate Chip cookie',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 2,
    name: 'Chocolate Chip (with Sprinkles)',
    image: './images/chocolatechipsprinkles.webp',
    description: 'A delicious soft chocolate Chip cookie with added sprinkles',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 3,
    name: 'White Chocolate Chip',
    image: './images/whitechocolatechip.jpg',
    description: 'Indulge in the golden crunch of our buttery butterscotch cookie',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 4,
    name: 'Mix Chocolate Chip',
    image: './images/chocolatechip_wb.jpg',
    description: 'Indulge in the golden crunch of our buttery butterscotch cookie',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 5,
    name: 'Cinemon',
    image: './images/sugarcookie.jpg',
    description: 'A delicious cookie with cinemon sugar',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 6,
    name: 'ButterScotch',
    image: './images/butterscotch_cc.jpg',
    description: 'Indulge in the golden crunch of our buttery butterscotch cookie',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 7,
    name: 'Snicker Doodle',
    image: './images/snickerdoodle.jpg',
    description: 'Indulge in the golden crunch of our buttery butterscotch cookie',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
  {
    _id: 8,
    name: 'Double Chocolate Chip',
    image: './images/doublechoc.jpg',
    description: 'Enjoy in the golden crunch of our double chocolate chip cookie',
    price: 2.5,
    inStock: true,
    rating: 0,
    numReviews: 0,
  },
];

export default products;
